/**
 * nav.test.mjs — the shared site-header nav (Campus / Issues / Editor)
 * appears, with a working relative link to the editor, on every real page
 * this project ships — plus room-scaffold.js's generateRoomHtml(), so a
 * brand-new room the editor creates gets it too, not just the 5 existing
 * ones. There's no shared template/partial (this is a static, no-build-step
 * site — see README), so each page's copy is checked independently; nothing
 * here should let one page's header drift from the rest.
 * Run: node test/nav.test.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.join(import.meta.dirname, '..');
const results = [];

const { generateRoomHtml } = await import('../js/editor/room-scaffold.js');

function readFile(rel) {
  return fs.readFileSync(path.join(ROOT, rel), 'utf8');
}

async function test(name, fn) {
  try { await fn(); results.push(['PASS', name, '']); }
  catch (err) { results.push(['FAIL', name, err.message]); }
}
function assert(cond, msg) { if (!cond) throw new Error(msg); }

/** Pulls out just the <nav class="site-nav">…</nav> block, so a match
 *  elsewhere on the page (e.g. body content that happens to mention
 *  "editor.html") can never produce a false pass. */
function siteNavOf(html) {
  const m = /<nav class="site-nav"[^>]*>([\s\S]*?)<\/nav>/.exec(html);
  assert(m, 'expected a <nav class="site-nav"> block in this page');
  return m[1];
}

const PAGES_EXPECTING_RELATIVE_EDITOR_LINK = [
  ['index.html', 'editor.html'],
  ['issues.html', 'editor.html'],
  ['rooms/commons.html', '../editor.html'],
  ['rooms/annex.html', '../editor.html'],
  ['rooms/workshop.html', '../editor.html'],
  ['rooms/b2-204.html', '../editor.html'],
  ['rooms/b2-210.html', '../editor.html'],
];

for (const [rel, href] of PAGES_EXPECTING_RELATIVE_EDITOR_LINK) {
  await test(`${rel}'s site header nav links to the editor (${href}), alongside Campus/Issues`, async () => {
    const nav = siteNavOf(readFile(rel));
    assert(nav.includes('Campus</a>'), `${rel}: expected the existing Campus link to still be there`);
    assert(nav.includes('Issues</a>'), `${rel}: expected the existing Issues link to still be there`);
    assert(nav.includes(`href="${href}"`) && nav.includes('>Editor</a>'), `${rel}: expected an Editor link (${href}) in the site nav, got: ${nav.trim()}`);
  });
}

await test('editor.html\'s own site header nav includes an Editor entry too, marked as the current page', async () => {
  const nav = siteNavOf(readFile('editor.html'));
  assert(nav.includes('Campus</a>'), 'expected the existing Campus link to still be there');
  assert(nav.includes('Issues</a>'), 'expected the existing Issues link to still be there');
  assert(/href="editor\.html"[^>]*aria-current="page"[^>]*>Editor</.test(nav) || /aria-current="page"[^>]*href="editor\.html"[^>]*>Editor</.test(nav),
    `expected editor.html's own Editor nav entry to carry aria-current="page", got: ${nav.trim()}`);
});

await test('a brand-new room generated by the editor (generateRoomHtml) also gets the Editor nav entry', async () => {
  const html = generateRoomHtml({ id: 'NAVTEST', label: 'Nav Test', campus: 'Test Site', dataUrl: '../data/navtest.json' });
  const nav = siteNavOf(html);
  assert(nav.includes('href="../editor.html"') && nav.includes('>Editor</a>'), `expected a new room's own page shell to already include the Editor nav link, got: ${nav.trim()}`);
});

/* ── Report ────────────────────────────────────────────────────────── */

const failed = results.filter(r => r[0] === 'FAIL');
for (const [status, name, msg] of results) {
  console.log(`${status === 'PASS' ? ' ok ' : 'FAIL'}  ${name}${msg ? `\n        → ${msg}` : ''}`);
}
console.log(`\n${results.length - failed.length}/${results.length} passing`);
process.exit(failed.length ? 1 : 0);
